### ISSUE TITLE
Wrong service_name is logged for response

### ISSUE THREAD

**Issue by MMoisa** [Financial-Times/content-preview#24]
After the application calls the methode-api endpoint the wrong `service_name` is logged in the response. The application logs `methode-article-mapper` as the `service_name` no matter what endpoint is actually called.

**Comment by tosan88** [comment]
<s>I see this is solved by https://github.com/Financial-Times/content-preview/pull/16</s> Actually no, I misread it, this is what I'm currently working on :))

**Comment by tosan88** [comment]
Handled by https://github.com/Financial-Times/content-preview/pull/27
